// USED GENERALLY
export const CONTENT_PADDING = 8

// USED FOR SIDEBAR + STATUSBAR
export const SCROLLBAR_PADDING = 12
export const HEADER_HEIGHT = 56
export const SIDE_OPEN_W = 216
export const NAV_ITEM_HEIGHT = 36

// USED FOR CHAT
export const CHAT_HEADER = 36
